name: syncdraw # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: SyncDraw - the ANSI drawing app
description: |
  SyncDraw - the ANSI drawing app

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  syncdraw_icon.png
title: SyncDraw

apps:
  syncdraw:
    command: syncdraw
  buildfont:
    command: buildfont
  fontutil:
    command: fontutil
parts:
  syncdraw:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      syncdraw: build/
      syncdraw.1: man/man1/

architectures:
  - build-on: amd64

